export function MovingForwardFutureBrightNcWrestlingPart4Content() {
  return (
    <div className="space-y-10">
      <section><p>The 2025 USMC Nationals in Fargo served as both a benchmark and a learning experience for Team North Carolina. The state left the FargoDome proud of its athletes and more determined to build with greater intention, experience, knowledge and effort.</p><p>The future was bright, but continued progress required year-round work and more high-level competitive repetitions.</p></section>

      <section><h2>Jamel Johnson challenged Team NC</h2><p>Greco-Roman closed the week in Fargo. Before the final tournament, North Carolina native and U.S. Greco-Roman National Team member Jamel Johnson addressed the team with a message centered on unwavering belief.</p><div className="not-prose rounded-xl border border-slate-200 bg-slate-50 p-6"><h3 className="font-bold text-[#13294B]">Jamel Johnson</h3><dl className="mt-4 grid gap-3 text-sm sm:grid-cols-2"><div><dt className="font-bold text-slate-900">Style</dt><dd className="text-slate-600">Greco-Roman</dd></div><div><dt className="font-bold text-slate-900">Primary weight</dt><dd className="text-slate-600">72 kg, with competition at 70 kg and 67 kg</dd></div><div><dt className="font-bold text-slate-900">Affiliations</dt><dd className="text-slate-600">U.S. Army WCAP, U.S. Marine Corps and NW Spartans</dd></div><div><dt className="font-bold text-slate-900">Selected achievement</dt><dd className="text-slate-600">2021 Pan American champion at 72 kg</dd></div></dl></div><p>Johnson was known for breaking matches into focused 30-second intervals and emphasizing mental and emotional preparation alongside physical training.</p></section>

      <section><h2>Competitive fire in Greco-Roman</h2><p>Team NC responded the next morning with energy across the Junior and 16U divisions. Technical gaps cost some matches, while relentless effort carried other wrestlers through difficult positions.</p><p>Drew Teeter in 16U and Troy Shannon in the Junior division made deep runs that ended just short of the podium. Aaron Ellison broke through in the 16U 150-pound blood round to earn All-America honors and bring home a Fargo stop sign.</p></section>

      <section><h2>High-level repetitions mattered</h2><p>Ellison&apos;s podium finish followed a demanding competitive schedule that included NHSCA Nationals, the U.S. Open, Southeast Regionals, 16U Duals and a previous Fargo appearance.</p><p>Faith Bane&apos;s own Fargo success came after competition at Journeymen World Classic, Super 32, USMC Women&apos;s Nationals in Spokane and the U.S. Open in Las Vegas.</p><div className="not-prose rounded-xl bg-[#13294B] p-6 text-white"><div className="text-xl font-black text-[#D3B574]">The shared lesson</div><p className="mt-2 leading-7">Consistent exposure to elite opponents prepared athletes for the pressure, pace and adjustments required to reach national podiums.</p></div></section>

      <section><h2>Moving forward</h2><p>Team North Carolina&apos;s next step was not simply to work harder, but to train with greater purpose: develop international-style technique, compete more frequently against elite opponents and build the mental habits required for Fargo&apos;s biggest moments.</p><p>The foundation had been established. Sustained national progress would come from intention, discipline and year-round high-level experience.</p></section>
    </div>
  )
}
