import Link from "next/link"

export function NcUnitedWrestlingGuildPremierPartnerContent() {
  return (
    <div className="space-y-10">
      <section>
        <p>
          <strong>RALEIGH, N.C. — August 9, 2026</strong> — NC United Wrestling today announced <strong>The Wrestling
          Guild</strong> as a Premier Partner of the 2026 <strong>Tournament of Champions</strong>, taking place
          September 18–19 in Apex, North Carolina.
        </p>
        <p>
          The Wrestling Guild has committed <strong>$1,000 to the event</strong>, with 100% of Tournament of Champions
          partnership and sponsorship dollars going directly back into the North Carolina wrestling community.
        </p>
        <p>
          The partnership brings together two organizations with a shared vision: create more opportunities for
          wrestlers, connect the wrestling community, and better utilize the incredible resources already available
          across North Carolina.
        </p>
      </section>

      <section>
        <h2>Tapping Into North Carolina&apos;s Wrestling Superpower</h2>
        <p>
          North Carolina has something special in its backyard: outstanding college wrestling programs and
          accomplished athletes competing and training at the highest levels of the sport.
        </p>
        <p>The Wrestling Guild was created in part to make that resource more accessible.</p>
        <p>
          The Guild is a wrestling training marketplace where families can discover and book <strong>elite coaches
          for private lessons and small-group training</strong>, with a heavy focus on current and former NCAA
          wrestlers.
        </p>
        <p>
          For families, it creates easier access to high-level instruction and mentorship. For coaches and college
          athletes, it provides a platform to share their knowledge, connect with the next generation of wrestlers,
          and earn income through the sport.
        </p>
        <p>
          <strong>
            Some of the best wrestling knowledge in the country is already in our backyard. The Guild helps connect
            wrestlers to it.
          </strong>
        </p>
      </section>

      <section>
        <h2>More Than Training</h2>
        <p>The Wrestling Guild&apos;s vision extends beyond the training room.</p>
        <p>
          The platform is building a broader marketplace specifically for the wrestling community, giving users a
          place to <strong>buy, sell, and trade wrestling shoes, team-issued gear, apparel, and other wrestling
          equipment.</strong>
        </p>
        <p>
          The goal is to create one destination built around wrestling — connecting athletes, families, and coaches
          with training, gear, resources, and opportunities within the sport.
        </p>
        <p>
          <strong>Train. Connect. Elevate.</strong>
        </p>
      </section>

      <section>
        <h2>Investing Back Into North Carolina Wrestling</h2>
        <p>
          That mission closely aligns with NC United&apos;s broader effort to strengthen the wrestling ecosystem across
          North Carolina — athletes, coaches, clubs, college programs, and the communities that support them.
        </p>
        <p>The Tournament of Champions partnership program follows that same philosophy.</p>
        <p>
          <strong>
            100% of partnership and sponsorship dollars generated by the Tournament of Champions go directly back
            into the North Carolina wrestling community
          </strong>{" "}
          — supporting athletes, creating opportunities, improving the event experience, and helping continue to grow
          the sport across the state.
        </p>
        <p>
          The Wrestling Guild becomes the Tournament of Champions&apos; first Premier Partner with its <strong>$1,000
          commitment to North Carolina wrestling.</strong>
        </p>
      </section>

      <section>
        <h2>Join The Wrestling Guild</h2>
        <p>
          Creating an account is <strong>free</strong>.
        </p>
        <p>
          Wrestlers and families can sign up to discover coaches, explore private and small-group training
          opportunities, and access the growing wrestling marketplace.
        </p>
        <p>
          For coaches — including current and former NCAA athletes — The Guild provides an opportunity to offer
          training, share their experience, and connect directly with wrestlers looking to improve.
        </p>
        <p>
          <strong>
            North Carolina doesn&apos;t need to look far for elite wrestling resources. Many of them are already here.
          </strong>
        </p>
        <p>
          <a href="https://www.wrestlingguild.com/">Create a free Wrestling Guild account</a>
        </p>
      </section>

      <section>
        <div className="not-prose rounded-xl border border-[#D3B574]/30 bg-[#13294B] p-6 text-center text-white sm:p-8">
          <p className="text-sm font-bold uppercase tracking-[0.18em] text-[#D3B574]">
            The Wrestling Guild × NC United
          </p>
          <p className="mt-3 text-xl font-black sm:text-2xl">2026 Tournament of Champions Premier Partner</p>
          <p className="mt-2 text-sm text-white/70">September 18–19 · Apex, North Carolina</p>
          <Link
            href="/tournament-of-champions"
            className="mt-5 inline-flex rounded-lg bg-[#D3B574] px-5 py-3 text-sm font-bold text-[#13294B] no-underline"
          >
            Explore the Tournament of Champions
          </Link>
        </div>
      </section>
    </div>
  )
}
