// Mock data for athletes
export const mockAthletes = [
  {
    id: "dfd4f4e2-f104-47fa-9987-6b5baeb18d7c",
    name: "Hayden Haynes",
    firstName: "Hayden",
    lastName: "Haynes",
    highschool: "Cary High School",
    college: "NC State",
    division: "D1",
    weightclass: "157",
    graduationyear: 2024,
    commitmentdate: "2023-11-15",
    photourl: "/wrestler-profile.png",
    achievements: ["State Champion 2023", "All-American 2022", "Regional Champion"],
  },
  {
    id: "a1b2c3d4-e5f6-7890-1234-567890abcdef",
    name: "Jane Doe",
    firstName: "Jane",
    lastName: "Doe",
    highschool: "Apex High School",
    college: "UNC Chapel Hill",
    division: "D1",
    weightclass: "133",
    graduationyear: 2025,
    commitmentdate: "2023-10-20",
    photourl: "/diverse-wrestlers.png",
    achievements: ["Conference Champion", "Regional Qualifier"],
  },
  {
    id: "b2c3d4e5-f6a7-8901-2345-678901abcdef",
    name: "John Smith",
    firstName: "John",
    lastName: "Smith",
    highschool: "Green Hope High School",
    college: "Duke University",
    division: "D1",
    weightclass: "145",
    graduationyear: 2024,
    commitmentdate: "2023-09-10",
    photourl: "/diverse-wrestlers.png",
    achievements: ["3x State Qualifier", "2x Regional Champion"],
  },
]

// Mock data for colleges with athleteCount
export const mockColleges = [
  {
    id: 1,
    name: "NC State",
    location: "Raleigh, NC",
    division: "D1",
    conference: "ACC",
    logo: "/wolfpack-logo.png",
    athleteCount: 24,
  },
  {
    id: 2,
    name: "UNC Chapel Hill",
    location: "Chapel Hill, NC",
    division: "D1",
    conference: "ACC",
    logo: "/UNC_Chapel_Hill_Logo.png",
    athleteCount: 18,
  },
  {
    id: 3,
    name: "Appalachian State",
    location: "Boone, NC",
    division: "D1",
    conference: "SoCon",
    logo: "/appalachian-state-mountains.png",
    athleteCount: 15,
  },
  {
    id: 4,
    name: "Campbell University",
    location: "Buies Creek, NC",
    division: "D1",
    conference: "SoCon",
    logo: "/campbell-university-seal.png",
    athleteCount: 12,
  },
  {
    id: 5,
    name: "Queens University",
    location: "Charlotte, NC",
    division: "D2",
    conference: "SAC",
    logo: "/queens-university-shield.png",
    athleteCount: 9,
  },
  {
    id: 6,
    name: "Belmont Abbey",
    location: "Belmont, NC",
    division: "D2",
    conference: "Conference Carolinas",
    logo: "/belmont-abbey-architectural-detail.png",
    athleteCount: 7,
  },
  {
    id: 7,
    name: "UNC Pembroke",
    location: "Pembroke, NC",
    division: "D2",
    conference: "Conference Carolinas",
    logo: "/unc-pembroke-seal.png",
    athleteCount: 6,
  },
  {
    id: 8,
    name: "Greensboro College",
    location: "Greensboro, NC",
    division: "D3",
    conference: "USA South",
    logo: "/Greensboro-College-Seal.png",
    athleteCount: 4,
  },
]

// Mock data for high schools with athleteCount
export const mockHighSchools = [
  {
    id: 1,
    name: "Cary High School",
    location: "Cary, NC",
    conference: "South Wake 4A",
    logo: "/cary-high-school-spirit.png",
    athleteCount: 15,
  },
  {
    id: 2,
    name: "Hough High School",
    location: "Cornelius, NC",
    conference: "Queen City 4A",
    logo: "/hough-high-school-logo.png",
    athleteCount: 12,
  },
  {
    id: 3,
    name: "Cardinal Gibbons",
    location: "Raleigh, NC",
    conference: "CAP 6 4A",
    logo: "/cardinal-gibbons-crest.png",
    athleteCount: 10,
  },
  {
    id: 4,
    name: "Laney High School",
    location: "Wilmington, NC",
    conference: "Mideastern 4A",
    logo: "/Laney-High-Wildcats.png",
    athleteCount: 8,
  },
  {
    id: 5,
    name: "Jack Britt High School",
    location: "Fayetteville, NC",
    conference: "United 8 4A",
    logo: "/jack-britt-high-school-logo.png",
    athleteCount: 7,
  },
  {
    id: 6,
    name: "Green Hope High School",
    location: "Cary, NC",
    conference: "South Wake 4A",
    logo: "/generic-high-school-logo.png",
    athleteCount: 6,
  },
  {
    id: 7,
    name: "Panther Creek High School",
    location: "Cary, NC",
    conference: "South Wake 4A",
    logo: "/generic-high-school-logo.png",
    athleteCount: 5,
  },
]

// Updated wrestling clubs list with athleteCount
export const mockWrestlingClubs = [
  {
    id: 1,
    name: "RAW",
    location: "Raleigh, NC",
    logo: "/wrestling-club-logo.png",
    athleteCount: 18,
  },
  {
    id: 2,
    name: "Darkhorse",
    location: "Charlotte, NC",
    logo: "/wrestling-club-logo.png",
    athleteCount: 14,
  },
  {
    id: 3,
    name: "Capital City",
    location: "Raleigh, NC",
    logo: "/wrestling-club-logo.png",
    athleteCount: 12,
  },
  {
    id: 4,
    name: "Wolfpack",
    location: "Raleigh, NC",
    logo: "/wrestling-club-logo.png",
    athleteCount: 10,
  },
  {
    id: 5,
    name: "The Wrestling Academy",
    location: "Greensboro, NC",
    logo: "/wrestling-club-logo.png",
    athleteCount: 8,
  },
  {
    id: 6,
    name: "Elite 252",
    location: "Greenville, NC",
    logo: "/wrestling-club-logo.png",
    athleteCount: 7,
  },
  {
    id: 7,
    name: "Beastworks",
    location: "Charlotte, NC",
    logo: "/wrestling-club-logo.png",
    athleteCount: 6,
  },
  {
    id: 8,
    name: "The Factory",
    location: "Wilmington, NC",
    logo: "/wrestling-club-logo.png",
    athleteCount: 5,
  },
  {
    id: 9,
    name: "NC Pride",
    location: "Fayetteville, NC",
    logo: "/wrestling-club-logo.png",
    athleteCount: 4,
  },
  {
    id: 10,
    name: "Dynamic Elite",
    location: "Asheville, NC",
    logo: "/wrestling-club-logo.png",
    athleteCount: 3,
  },
]

// Complete wrestling clubs list for dropdowns
export const WRESTLING_CLUBS_LIST = [
  "Beastworks",
  "Believe 2 Achieve",
  "Believe to Achieve",
  "Braves",
  "Buies Creek", // Fixed spelling from "Buise Creek" to "Buies Creek"
  "C2X",
  "Capital City",
  "Clash Wrestling",
  "Combat",
  "D1",
  "Darkhorse",
  "Devil Dogs",
  "Dogtown",
  "Dynamic Elite",
  "East Carolina Wrestling Academy",
  "Elite 252",
  "Fear This",
  "Forge",
  "Grizzly",
  "Haywood Elite",
  "Iron Tide",
  "K-Vegas",
  "Mooresville",
  "Mustang",
  "NC Pride",
  "None",
  "OBX Wrestling Factory",
  "Port City Pirates",
  "RAW",
  "Red Lynx",
  "Relentless",
  "School of Hard Knocks",
  "Sly Fox",
  "Spartan",
  "Tar River",
  "The Factory",
  "The Wrestling Academy",
  "Trinity Top Team",
  "Unaffiliated",
  "Wolfpack",
  "Wolverine Wrestling Club",
  "Wrestling Warehouse",
  "CLUB IS NOT LISTED",
].sort()
