import type { NhscaDualsBigWin } from "@/lib/nhsca-duals-big-wins"

/** Curated Duals 2026 big wins — merged with admin "Big win" tags on the public portal. */
export const NHSCA_DUALS_2026_BIG_WINS: Omit<NhscaDualsBigWin, "id">[] = [
  // —— Select · Day 2 ——
  {
    wrestlerName: "Danny McDermott",
    weight: "120",
    opponentName: "Andrew Juliano",
    opponentTeam: "BlueWave",
    resultLabel: "DEC",
    scoreLine: null,
    roundName: "Consolation pool",
    dayName: "Day 2",
    teamType: "select",
    highlight: "NY state champion",
  },
  {
    wrestlerName: "Holt Quincy",
    weight: "126",
    opponentName: "Peter Filli",
    opponentTeam: "Day 2 dual",
    resultLabel: "DEC",
    scoreLine: null,
    roundName: "Consolation pool",
    dayName: "Day 2",
    teamType: "select",
    highlight: "NY state placer",
  },
  {
    wrestlerName: "Cole Shuster",
    weight: "138",
    opponentName: "Aidan Lee",
    opponentTeam: "Day 2 dual",
    resultLabel: "DEC",
    scoreLine: "9-6",
    roundName: "Consolation pool",
    dayName: "Day 2",
    teamType: "select",
    highlight: "NY state placer · NY commit",
  },

  // —— National · Day 2 ——
  {
    wrestlerName: "Ayden Sumners",
    weight: "126",
    opponentName: "Cedric Montgomery",
    opponentTeam: "Day 2 dual",
    resultLabel: "DEC",
    scoreLine: null,
    roundName: "Championship pool",
    dayName: "Day 2",
    teamType: "national",
    highlight: "GA state finalist",
  },
  {
    wrestlerName: "Mac Johnson",
    weight: "132",
    opponentName: "Walker Bunch",
    opponentTeam: "Day 2 dual",
    resultLabel: "FALL",
    scoreLine: null,
    roundName: "Championship pool",
    dayName: "Day 2",
    teamType: "national",
    highlight: "GA state champion",
  },
  {
    wrestlerName: "Tye Johnson",
    weight: "138",
    opponentName: "Trey Twilley",
    opponentTeam: "Day 2 dual",
    resultLabel: "DEC",
    scoreLine: "6-0",
    roundName: "Championship pool",
    dayName: "Day 2",
    teamType: "national",
    highlight: "3× FL state placer",
  },
  {
    wrestlerName: "Sammy Gantt",
    weight: "145",
    opponentName: "Cason Waddell",
    opponentTeam: "Day 2 dual",
    resultLabel: "DEC",
    scoreLine: null,
    roundName: "Championship pool",
    dayName: "Day 2",
    teamType: "national",
    highlight: "GA state finalist",
  },
  {
    wrestlerName: "Aidan Gore",
    weight: "152",
    opponentName: "TN state champion",
    opponentTeam: "Team Prestige",
    resultLabel: "DEC",
    scoreLine: "5-2",
    roundName: "Championship pool",
    dayName: "Day 2",
    teamType: "national",
    highlight: "#5 seed",
  },
  {
    wrestlerName: "Tobin McNair",
    weight: "160",
    opponentName: "Samir Ross",
    opponentTeam: "Day 2 dual",
    resultLabel: "DEC",
    scoreLine: null,
    roundName: "Championship pool",
    dayName: "Day 2",
    teamType: "national",
    highlight: "GA state 3rd",
  },
  {
    wrestlerName: "Dominic Blue",
    weight: "170",
    opponentName: "Joseph Foalima",
    opponentTeam: "Day 2 dual",
    resultLabel: "DEC",
    scoreLine: "7-2",
    roundName: "Championship pool",
    dayName: "Day 2",
    teamType: "national",
    highlight: "FL state 3rd",
  },
  {
    wrestlerName: "Brieon Mayfield",
    weight: "182",
    opponentName: "Kevin Kilpatrick",
    opponentTeam: "Day 2 dual",
    resultLabel: "DEC",
    scoreLine: "7-3",
    roundName: "Championship pool",
    dayName: "Day 2",
    teamType: "national",
    highlight: "GA state champion",
  },
  {
    wrestlerName: "Keyshon Morrison",
    weight: "285",
    opponentName: "Grey Richardson",
    opponentTeam: "Day 2 dual",
    resultLabel: "FALL",
    scoreLine: null,
    roundName: "Championship pool",
    dayName: "Day 2",
    teamType: "national",
    highlight: "2× GA state placer · NHSCA All-American",
  },
  {
    wrestlerName: "Keyshon Morrison",
    weight: "285",
    opponentName: "Landon Jackson",
    opponentTeam: "Day 2 dual",
    resultLabel: "DEC",
    scoreLine: null,
    roundName: "Championship pool",
    dayName: "Day 2",
    teamType: "national",
    highlight: "SC state champion · NHSCA senior national champion",
  },
]
