/** Shared Tailwind overrides for public profiles on navy (#0A1628 / #0f1c2e) backgrounds. */
export const PROFILE_DARK_THEME = [
  "[&_.profile-card]:border-white/10 [&_.profile-card]:bg-[#0f1c2e]",
  "[&_.profile-card-body]:bg-[#0f1c2e] [&_.profile-card-body]:text-white/80",
  "[&_.profile-panel]:border-white/10 [&_.profile-panel]:bg-white/5",
  "[&_.profile-text]:!text-white",
  "[&_.profile-text-muted]:!text-white/50",
  "[&_.profile-label]:!text-white/40",
  "[&_.profile-headline]:!text-[#D3B574]",
  "[&_.profile-card-body_h3]:!text-white",
  "[&_.profile-card-body_ul]:!text-white/80",
  "[&_.profile-card-body_.text-gray-900]:!text-white",
  "[&_.profile-card-body_.text-gray-700]:!text-white/80",
  "[&_.profile-card-body_.text-gray-600]:!text-white/60",
  "[&_.profile-card-body_.text-gray-500]:!text-white/50",
  "[&_.profile-card-body_.text-gray-400]:!text-white/40",
  "[&_.profile-card-body_.text-gray-200]:!text-white/70",
  "[&_.profile-card-body_.text-\\[\\#002147\\]]:!text-white",
  "[&_.profile-card-body_.bg-gray-50]:!bg-white/5 [&_.profile-card-body_.bg-gray-50]:!border-white/10",
  "[&_.profile-card-body_.bg-blue-50]:!bg-white/10 [&_.profile-card-body_.border-blue-200]:!border-white/10",
  "[&_.profile-card-body_.text-blue-700]:!text-white/70",
  "[&_.profile-card-body_.text-amber-700]:!text-[#D3B574]",
  "[&_.profile-card-body_a.text-blue-600]:!text-[#D3B574] hover:[&_.profile-card-body_a.text-blue-600]:!text-[#D3B574]/80",
  "[&_.profile-panel_.bg-gray-50]:!bg-white/10 [&_.profile-panel_.border-gray-200]:!border-white/10",
  "[&_.profile-match-data_.bg-white]:!bg-[#0f1c2e] [&_.profile-match-data_.bg-white]:!border [&_.profile-match-data_.bg-white]:!border-white/10",
  "[&_.profile-match-data_.text-gray-900]:!text-white",
  "[&_.profile-match-data_.text-gray-800]:!text-white/80",
  "[&_.profile-match-data_.text-gray-600]:!text-white/60",
  "[&_.profile-match-data_.text-gray-500]:!text-white/50",
  "[&_.profile-match-data_.bg-gray-50]:!bg-white/5",
  "[&_.profile-match-data_.bg-gray-100]:!bg-white/10",
  "[&_.profile-match-data_.bg-gray-200]:!bg-white/20",
  "[&_.profile-match-data_.divide-gray-200]:!divide-white/10",
  "[&_.profile-match-data_.hover\\:bg-gray-50:hover]:!bg-white/5",
].join(" ")
