import { NextResponse } from "next/server"
import { createClient } from "@/lib/supabase/server"

/**
 * One-time setup: create nchsaa_bracket_images table.
 * GET /api/run-script/create-nchsaa-bracket-images-table (admin only).
 * Or run the SQL below in Supabase SQL Editor.
 */
const CREATE_TABLE_SQL = `
CREATE TABLE IF NOT EXISTS nchsaa_bracket_images (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  year INT NOT NULL,
  classification TEXT NOT NULL,
  weight_class TEXT NOT NULL,
  image_url TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (year, classification, weight_class)
);
CREATE INDEX IF NOT EXISTS idx_nchsaa_bracket_images_lookup
  ON nchsaa_bracket_images (year, classification, weight_class);
`

export async function GET() {
  try {
    const supabase = await createClient()
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
    const { data: profile } = await supabase.from("user_profiles").select("is_admin").eq("user_id", user.id).single()
    if (!profile?.is_admin) return NextResponse.json({ error: "Forbidden" }, { status: 403 })

    return NextResponse.json({
      message: "Run the SQL below once in Supabase → SQL Editor to create nchsaa_bracket_images.",
      sql: CREATE_TABLE_SQL.trim(),
    })
  } catch (e) {
    console.error(e)
    return NextResponse.json({ error: String(e) }, { status: 500 })
  }
}
