import { NextResponse } from "next/server"
import { createClient } from "@/lib/supabase/server"

/**
 * One-time setup: create NCHSAA article reactions and comments tables.
 * GET as admin returns SQL to run in Supabase SQL Editor.
 */
const SQL = `
-- Article reactions (thumbs up/down per article)
CREATE TABLE IF NOT EXISTS nchsaa_article_reactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  article_slug TEXT NOT NULL,
  reaction TEXT NOT NULL CHECK (reaction IN ('up', 'down')),
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  guest_id TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_article_reactions_slug ON nchsaa_article_reactions(article_slug);

-- Comments (top-level and replies)
CREATE TABLE IF NOT EXISTS nchsaa_article_comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  article_slug TEXT NOT NULL,
  parent_id BIGINT REFERENCES nchsaa_article_comments(id) ON DELETE CASCADE,
  author_name TEXT NOT NULL,
  author_email TEXT,
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_article_comments_slug ON nchsaa_article_comments(article_slug);
CREATE INDEX IF NOT EXISTS idx_article_comments_parent ON nchsaa_article_comments(parent_id);

-- Comment reactions (thumbs up/down per comment)
CREATE TABLE IF NOT EXISTS nchsaa_comment_reactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  comment_id BIGINT NOT NULL REFERENCES nchsaa_article_comments(id) ON DELETE CASCADE,
  reaction TEXT NOT NULL CHECK (reaction IN ('up', 'down')),
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  guest_id TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_comment_reactions_comment ON nchsaa_comment_reactions(comment_id);

ALTER TABLE nchsaa_article_reactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE nchsaa_article_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE nchsaa_comment_reactions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "nchsaa_article_reactions_select" ON nchsaa_article_reactions;
CREATE POLICY "nchsaa_article_reactions_select" ON nchsaa_article_reactions FOR SELECT USING (true);
DROP POLICY IF EXISTS "nchsaa_article_reactions_insert" ON nchsaa_article_reactions;
CREATE POLICY "nchsaa_article_reactions_insert" ON nchsaa_article_reactions FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "nchsaa_article_reactions_delete" ON nchsaa_article_reactions;
CREATE POLICY "nchsaa_article_reactions_delete" ON nchsaa_article_reactions FOR DELETE USING (true);

DROP POLICY IF EXISTS "nchsaa_article_comments_select" ON nchsaa_article_comments;
CREATE POLICY "nchsaa_article_comments_select" ON nchsaa_article_comments FOR SELECT USING (true);
DROP POLICY IF EXISTS "nchsaa_article_comments_insert" ON nchsaa_article_comments;
CREATE POLICY "nchsaa_article_comments_insert" ON nchsaa_article_comments FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "nchsaa_article_comments_delete" ON nchsaa_article_comments;
CREATE POLICY "nchsaa_article_comments_delete" ON nchsaa_article_comments FOR DELETE USING (true);

DROP POLICY IF EXISTS "nchsaa_comment_reactions_select" ON nchsaa_comment_reactions;
CREATE POLICY "nchsaa_comment_reactions_select" ON nchsaa_comment_reactions FOR SELECT USING (true);
DROP POLICY IF EXISTS "nchsaa_comment_reactions_insert" ON nchsaa_comment_reactions;
CREATE POLICY "nchsaa_comment_reactions_insert" ON nchsaa_comment_reactions FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "nchsaa_comment_reactions_delete" ON nchsaa_comment_reactions;
CREATE POLICY "nchsaa_comment_reactions_delete" ON nchsaa_comment_reactions FOR DELETE USING (true);
`

export async function GET() {
  try {
    const supabase = await createClient()
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
    const { data: profile } = await supabase.from("user_profiles").select("is_admin").eq("user_id", user.id).single()
    if (!profile?.is_admin) return NextResponse.json({ error: "Forbidden" }, { status: 403 })
    return NextResponse.json({ message: "Run the SQL below in Supabase → SQL Editor.", sql: SQL.trim() })
  } catch (e) {
    console.error(e)
    return NextResponse.json({ error: String(e) }, { status: 500 })
  }
}
