#!/usr/bin/env python3
"""
Generate PostgreSQL INSERTs for public.events from nc-united-events-export.csv
(legacy calendar export: UUID ids and no start_date column).

Usage:
  python3 scripts/generate-events-import-from-csv.py ~/Downloads/nc-united-events-export.csv > scripts/nc-united-events-import-generated.sql

Then run the .sql in Supabase SQL Editor (review first — dates are inferred).

Date logic:
  1) Parse M/D or M/D/YYYY from title when present (year from match or Created At).
  2) Else use the date part of Created At.
"""

from __future__ import annotations

import csv
import re
import sys
from datetime import datetime
from pathlib import Path


def sql_str(s: str | None) -> str:
    if s is None:
        return "NULL"
    return "'" + s.replace("'", "''") + "'"


def parse_created(created: str) -> datetime | None:
    if not created or not created.strip():
        return None
    t = created.strip()
    try:
        if t.endswith("Z"):
            t = t[:-1] + "+00:00"
        # Postgres / CSV may use variable fractional seconds; Python needs valid ISO
        t = re.sub(r"\.\d+(?=[\+\-]|$)", "", t)
        return datetime.fromisoformat(t.replace("Z", "+00:00"))
    except ValueError:
        return None


def infer_start_date(title: str, created: str) -> str:
    dt_created = parse_created(created)
    # Prefer season year from Created At; default 2025 for legacy exports without timestamp
    year_ref = dt_created.year if dt_created else 2025

    # Title patterns: "9/28", "10/26/2025", "11/2"
    m = re.search(r"\b(\d{1,2})[\/\-](\d{1,2})(?:[\/\-](\d{2,4}))?\b", title)
    if m:
        mo, day = int(m.group(1)), int(m.group(2))
        yraw = m.group(3)
        if yraw:
            yr = int(yraw)
            if yr < 100:
                yr += 2000
        else:
            yr = year_ref
        try:
            return f"{yr:04d}-{mo:02d}-{day:02d}"
        except Exception:
            pass

    if dt_created:
        return dt_created.strftime("%Y-%m-%d")
    return "2025-01-01"


def norm_time(t: str | None) -> str | None:
    if not t or not str(t).strip():
        return None
    s = str(t).strip()
    # Expect HH:MM:SS or HH:MM
    if re.match(r"^\d{1,2}:\d{2}(:\d{2})?$", s):
        parts = s.split(":")
        if len(parts) == 2:
            return f"{int(parts[0]):02d}:{parts[1]}:00"
        return f"{int(parts[0]):02d}:{parts[1]}:{parts[2]}"
    return s[:32]


ALLOWED_CATS = {
    "blue-practice",
    "gold-practice",
    "training-camp",
    "ncu-dual-tournament",
    "national-tournament",
    "podcast",
    "important-date",
    "college-open",
    "ncaa-recruiting",
}


def main() -> None:
    path = Path(sys.argv[1]) if len(sys.argv) > 1 else Path.home() / "Downloads" / "nc-united-events-export.csv"
    if not path.is_file():
        print(f"-- File not found: {path}", file=sys.stderr)
        sys.exit(1)

    with path.open(newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        rows = list(reader)

    print("-- Generated by scripts/generate-events-import-from-csv.py")
    print("-- Review start_date values (inferred from title M/D when present, else Created At date).")
    print("-- If public.events already has rows, TRUNCATE ... CASCADE will remove linked drop_in_requests — or delete duplicates manually.")
    print("BEGIN;")
    print()

    for r in rows:
        title = (r.get("Title") or "").strip()
        if not title:
            continue
        desc = (r.get("Description") or "").strip() or None
        loc = (r.get("Location") or "").strip() or None
        cat = (r.get("Category") or "").strip() or "important-date"
        if cat not in ALLOWED_CATS:
            cat = "important-date"
        st = norm_time(r.get("Start Time"))
        et = norm_time(r.get("End Time"))
        logo = (r.get("Logo URL") or "").strip() or None
        reg = (r.get("Registration Link") or "").strip() or None
        created = (r.get("Created At") or "").strip()
        start_date = infer_start_date(title, created)
        dt_c = parse_created(created)
        if dt_c:
            created_sql = sql_str(dt_c.isoformat())
        else:
            created_sql = "NOW()"

        print(
            "INSERT INTO public.events (title, start_date, end_date, start_time, end_time, category, "
            "location, description, coach, registration_deadline, entry_fee, travel_info, weight_classes, "
            "rsvp_required, external_link, logo_url, drop_in_registration_link, max_drop_ins, created_at, updated_at)"
        )
        print(
            "VALUES ("
            f"{sql_str(title)}, "
            f"{sql_str(start_date)}::date, "
            "NULL, "
            f"{sql_str(st) if st else 'NULL'}, "
            f"{sql_str(et) if et else 'NULL'}, "
            f"{sql_str(cat)}, "
            f"{sql_str(loc) if loc else 'NULL'}, "
            f"{sql_str(desc) if desc else 'NULL'}, "
            "NULL, NULL, NULL, NULL, "  # coach, registration_deadline, entry_fee, travel_info
            "NULL, "  # weight_classes
            "false, "
            "NULL, "  # external_link
            f"{sql_str(logo) if logo else 'NULL'}, "
            f"{sql_str(reg) if reg else 'NULL'}, "
            "10, "
            f"{created_sql}::timestamptz, "
            "NOW()"
            ");"
        )
        print()

    print("COMMIT;")


if __name__ == "__main__":
    main()
