#!/usr/bin/env python3
"""
Generate Supabase SQL to gap-fill 2026 state QUALIFIERS (place = 0) from
2026_NCHSAA_State_Wrestlers.xlsx — WITHOUT touching existing placer rows.

Skips insert when ANY row exists for year=2026 + classification + weight_class
with same wrestler (dual-token ILIKE on wrestler_name).

Usage:
  python3 scripts/generate-2026-sq-gap-fill-sql.py ~/Downloads/2026_NCHSAA_State_Wrestlers.xlsx > /tmp/sq-gap.sql
  # Review, then run in Supabase SQL Editor.
"""

from __future__ import annotations

import re
import sys
import zipfile
import xml.etree.ElementTree as ET
from pathlib import Path

YEAR = 2026
PLACE_SQ = 0

NS = {"m": "http://schemas.openxmlformats.org/spreadsheetml/2006/main"}


def strip_ns(tag: str) -> str:
    return tag.split("}")[-1] if "}" in tag else tag


def cell_text(cell: ET.Element) -> str:
    out: list[str] = []
    for ch in cell:
        tag = strip_ns(ch.tag)
        if tag == "v":
            out.append(ch.text or "")
        elif tag == "is":
            for tch in ch:
                if strip_ns(tch.tag) == "t":
                    out.append(tch.text or "")
    return "".join(out)


def read_xlsx_rows(path: Path) -> list[dict[str, str]]:
    z = zipfile.ZipFile(path)
    xml = z.read("xl/worksheets/sheet1.xml").decode("utf-8")
    root = ET.fromstring(xml)
    rows: dict[int, dict[str, str]] = {}
    for row in root.findall(".//m:sheetData/m:row", NS):
        r_idx = int(row.attrib["r"])
        rowd: dict[str, str] = {}
        for c in row.findall("m:c", NS):
            ref = c.attrib["r"]
            col = "".join(x for x in ref if x.isalpha())
            rowd[col] = cell_text(c)
        rows[r_idx] = rowd

    records: list[dict[str, str]] = []
    for ri in sorted(rows.keys()):
        if ri < 2:
            continue
        r = rows[ri]
        name = (r.get("A") or "").strip()
        if not name:
            continue
        records.append(
            {
                "name": name,
                "school": (r.get("B") or "").strip(),
                "division": (r.get("C") or "").strip(),
                "weight": (r.get("D") or "").strip(),
                "gender": (r.get("E") or "").strip(),
            },
        )
    return records


def sql_escape(s: str) -> str:
    return (s or "").replace("'", "''")


def first_last_tokens(display_name: str) -> tuple[str, str] | None:
    raw = (display_name or "").strip()
    if not raw:
        return None
    suffixes = {"jr", "sr", "ii", "iii", "iv", "v", "2nd", "3rd", "4th"}
    parts = raw.split()
    while len(parts) >= 2:
        t = parts[-1].replace(".", "").lower()
        if t in suffixes:
            parts = parts[:-1]
        else:
            break
    if len(parts) < 2:
        return None
    return parts[0], parts[-1]


def normalize_weight(w: str) -> str:
    w = (w or "").strip()
    w = re.sub(r"\s*lbs?\s*$", "", w, flags=re.I)
    return w


def main() -> None:
    if len(sys.argv) < 2:
        print("Usage: python3 scripts/generate-2026-sq-gap-fill-sql.py <path-to-xlsx>", file=sys.stderr)
        sys.exit(1)
    path = Path(sys.argv[1]).expanduser()
    if not path.is_file():
        print(f"File not found: {path}", file=sys.stderr)
        sys.exit(1)

    records = read_xlsx_rows(path)
    print("-- Generated by scripts/generate-2026-sq-gap-fill-sql.py")
    print("-- Gap-fill place=0 only; NOT EXISTS skips if placer or SQ already present for same name tokens.")
    print("-- No transaction wrapper: each statement commits independently in the SQL Editor.")
    n = 0
    for rec in records:
        fl = first_last_tokens(rec["name"])
        if not fl:
            continue
        first, last = fl
        cls = rec["division"].strip()
        wt = normalize_weight(rec["weight"])
        school = rec["school"]
        wname = rec["name"]
        if not cls or not wt:
            continue

        first_e = sql_escape(first)
        last_e = sql_escape(last)
        cls_e = sql_escape(cls)
        wt_e = sql_escape(wt)
        name_e = sql_escape(wname)
        school_e = sql_escape(school)

        print(
            f"""INSERT INTO public.wrestling_nchsaa_results (year, classification, weight_class, place, wrestler_name, school)
SELECT {YEAR}, '{cls_e}', '{wt_e}', {PLACE_SQ}, '{name_e}', '{school_e}'
WHERE NOT EXISTS (
  SELECT 1
  FROM public.wrestling_nchsaa_results e
  WHERE e.year = {YEAR}
    AND e.classification = '{cls_e}'
    AND trim(both from e.weight_class::text) = '{wt_e}'
    AND e.wrestler_name ILIKE '%{first_e}%'
    AND e.wrestler_name ILIKE '%{last_e}%'
);"""
        )
        n += 1

    print(f"-- {n} INSERT statements (no-op when wrestler already has any row in that bracket).")


if __name__ == "__main__":
    main()
