-- Generated by scripts/generate-events-import-from-csv.py
-- Review start_date values (inferred from title M/D when present, else Created At date).
-- If public.events already has rows, TRUNCATE ... CASCADE will remove linked drop_in_requests — or delete duplicates manually.
BEGIN;

INSERT INTO public.events (title, start_date, end_date, start_time, end_time, category, location, description, coach, registration_deadline, entry_fee, travel_info, weight_classes, rsvp_required, external_link, logo_url, drop_in_registration_link, max_drop_ins, created_at, updated_at)
VALUES ('University of Virginia Team Practice', '2025-07-09'::date, NULL, '09:00:00', '17:00:00', 'training-camp', '210 Emmet Street South, Charlottesville, VA 22903', 'Invite Only practice with UVA Team', NULL, NULL, NULL, NULL, NULL, false, NULL, 'https://w8v0puzioqkz0xzh.public.blob.vercel-storage.com/event-logos/1752373129607.png', NULL, 10, '2025-07-09T17:46:55+00:00'::timestamptz, NOW());

INSERT INTO public.events (title, start_date, end_date, start_time, end_time, category, location, description, coach, registration_deadline, entry_fee, travel_info, weight_classes, rsvp_required, external_link, logo_url, drop_in_registration_link, max_drop_ins, created_at, updated_at)
VALUES ('Gold Team Practice @ NC State 9/28', '2025-09-28'::date, NULL, '11:00:00', '13:00:00', 'gold-practice', 'Weisiger-Brown Athletic Facility 2500 Warren Carroll Dr, Raleigh, NC 20607', NULL, NULL, NULL, NULL, NULL, NULL, false, NULL, NULL, NULL, 10, '2025-09-16T15:53:13+00:00'::timestamptz, NOW());

INSERT INTO public.events (title, start_date, end_date, start_time, end_time, category, location, description, coach, registration_deadline, entry_fee, travel_info, weight_classes, rsvp_required, external_link, logo_url, drop_in_registration_link, max_drop_ins, created_at, updated_at)
VALUES ('Gold Team Practice @ NC State 10/26', '2025-10-26'::date, NULL, '11:00:00', '13:00:00', 'gold-practice', 'Weisiger-Brown Athletic Facility 2500 Warren Carroll Dr, Raleigh, NC 20607', NULL, NULL, NULL, NULL, NULL, NULL, false, NULL, NULL, NULL, 10, '2025-09-16T15:58:03+00:00'::timestamptz, NOW());

INSERT INTO public.events (title, start_date, end_date, start_time, end_time, category, location, description, coach, registration_deadline, entry_fee, travel_info, weight_classes, rsvp_required, external_link, logo_url, drop_in_registration_link, max_drop_ins, created_at, updated_at)
VALUES ('Gold Team Practice @ NC State 10/12', '2025-10-12'::date, NULL, '11:00:00', '13:00:00', 'gold-practice', 'Weisiger-Brown Athletic Facility 2500 Warren Carroll Dr, Raleigh, NC 20607', NULL, NULL, NULL, NULL, NULL, NULL, false, NULL, NULL, NULL, 10, '2025-09-16T15:56:29+00:00'::timestamptz, NOW());

INSERT INTO public.events (title, start_date, end_date, start_time, end_time, category, location, description, coach, registration_deadline, entry_fee, travel_info, weight_classes, rsvp_required, external_link, logo_url, drop_in_registration_link, max_drop_ins, created_at, updated_at)
VALUES ('Gold Team Practice @ NC State', '2025-07-23'::date, NULL, '11:00:00', '13:00:00', 'gold-practice', 'NC State University – Weisiger-Brown Athletic Facility 2500 Warren Carroll Drive Raleigh, NC 27607', NULL, NULL, NULL, NULL, NULL, NULL, false, NULL, 'https://w8v0puzioqkz0xzh.public.blob.vercel-storage.com/event-logos/1753285802188.png', NULL, 10, '2025-07-23T15:50:02+00:00'::timestamptz, NOW());

INSERT INTO public.events (title, start_date, end_date, start_time, end_time, category, location, description, coach, registration_deadline, entry_fee, travel_info, weight_classes, rsvp_required, external_link, logo_url, drop_in_registration_link, max_drop_ins, created_at, updated_at)
VALUES ('Gold Team Practice @ NC State', '2025-07-23'::date, NULL, '11:00:00', '13:00:00', 'gold-practice', 'NC State University – Weisiger-Brown Athletic Facility 2500 Warren Carroll Drive Raleigh, NC 27607', NULL, NULL, NULL, NULL, NULL, NULL, false, NULL, 'https://w8v0puzioqkz0xzh.public.blob.vercel-storage.com/event-logos/1753285625450.png', NULL, 10, '2025-07-23T15:47:05+00:00'::timestamptz, NOW());

INSERT INTO public.events (title, start_date, end_date, start_time, end_time, category, location, description, coach, registration_deadline, entry_fee, travel_info, weight_classes, rsvp_required, external_link, logo_url, drop_in_registration_link, max_drop_ins, created_at, updated_at)
VALUES ('Gold Team Practice @ NC State', '2025-07-23'::date, NULL, '11:00:00', '13:00:00', 'gold-practice', 'NC State University – Weisiger-Brown Athletic Facility 2500 Warren Carroll Drive Raleigh, NC 27607', NULL, NULL, NULL, NULL, NULL, NULL, false, NULL, 'https://w8v0puzioqkz0xzh.public.blob.vercel-storage.com/event-logos/1753285545768.png', NULL, 10, '2025-07-23T15:45:46+00:00'::timestamptz, NOW());

INSERT INTO public.events (title, start_date, end_date, start_time, end_time, category, location, description, coach, registration_deadline, entry_fee, travel_info, weight_classes, rsvp_required, external_link, logo_url, drop_in_registration_link, max_drop_ins, created_at, updated_at)
VALUES ('Gold Team Practice @ NC State', '2025-07-23'::date, NULL, '11:00:00', '13:00:00', 'gold-practice', 'NC State University – Weisiger-Brown Athletic Facility 2500 Warren Carroll Drive Raleigh, NC 27607', NULL, NULL, NULL, NULL, NULL, NULL, false, NULL, 'https://w8v0puzioqkz0xzh.public.blob.vercel-storage.com/event-logos/1753285721511.png', NULL, 10, '2025-07-23T15:48:42+00:00'::timestamptz, NOW());

INSERT INTO public.events (title, start_date, end_date, start_time, end_time, category, location, description, coach, registration_deadline, entry_fee, travel_info, weight_classes, rsvp_required, external_link, logo_url, drop_in_registration_link, max_drop_ins, created_at, updated_at)
VALUES ('Gold Team Practice @ NC State 11/9', '2025-11-09'::date, NULL, '11:00:00', '13:00:00', 'gold-practice', 'Weisiger-Brown Athletic Facility 2500 Warren Carroll Dr, Raleigh, NC 20607', NULL, NULL, NULL, NULL, NULL, NULL, false, NULL, NULL, NULL, 10, '2025-09-16T16:00:51+00:00'::timestamptz, NOW());

INSERT INTO public.events (title, start_date, end_date, start_time, end_time, category, location, description, coach, registration_deadline, entry_fee, travel_info, weight_classes, rsvp_required, external_link, logo_url, drop_in_registration_link, max_drop_ins, created_at, updated_at)
VALUES ('Gold Team Practice at NC State 11/2', '2025-11-02'::date, NULL, '11:00:00', '13:00:00', 'gold-practice', 'Weisiger-Brown Athletic Facility 2500 Warren Carroll Dr, Raleigh, NC 20607', NULL, NULL, NULL, NULL, NULL, NULL, false, NULL, NULL, NULL, 10, '2025-09-16T15:59:27+00:00'::timestamptz, NOW());

INSERT INTO public.events (title, start_date, end_date, start_time, end_time, category, location, description, coach, registration_deadline, entry_fee, travel_info, weight_classes, rsvp_required, external_link, logo_url, drop_in_registration_link, max_drop_ins, created_at, updated_at)
VALUES ('2025 Elite Officials Clinic', '2025-07-31'::date, NULL, '12:00:00', '14:30:00', 'important-date', 'Hough High School', 'Great Opportunity: Give Back, Earn Some $, and Wrestle!

We’re looking for 6–8 wrestlers to help with a Referee Training Session at Hough High School on Saturday, August 23rd at 12:00 PM.

Wrestlers will assist with live match scenarios to help train referees on positions, scoring, and situations.

🌎 Referees from across the country, including NCAA Division I officials
💰 NC United will sponsor each volunteer with a $50 payment
🤝 Give Back to the Sport
💪 Get Extra Mat Time', NULL, NULL, NULL, NULL, NULL, false, NULL, 'https://w8v0puzioqkz0xzh.public.blob.vercel-storage.com/event-logos/1753965155983.png', NULL, 10, '2025-07-31T12:32:36+00:00'::timestamptz, NOW());

INSERT INTO public.events (title, start_date, end_date, start_time, end_time, category, location, description, coach, registration_deadline, entry_fee, travel_info, weight_classes, rsvp_required, external_link, logo_url, drop_in_registration_link, max_drop_ins, created_at, updated_at)
VALUES ('Blue Practice', '2025-12-16'::date, NULL, '13:00:00', '15:00:00', 'blue-practice', '210 South Road, Chapel Hill, NC 27599 ·', NULL, NULL, NULL, NULL, NULL, NULL, false, NULL, 'https://w8v0puzioqkz0xzh.public.blob.vercel-storage.com/event-logos/1765917580298.png', NULL, 10, '2025-12-16T20:39:40+00:00'::timestamptz, NOW());

INSERT INTO public.events (title, start_date, end_date, start_time, end_time, category, location, description, coach, registration_deadline, entry_fee, travel_info, weight_classes, rsvp_required, external_link, logo_url, drop_in_registration_link, max_drop_ins, created_at, updated_at)
VALUES ('Blue Team Practice @ NC State', '2025-07-10'::date, NULL, '13:00:00', '15:00:00', 'blue-practice', 'NC State Wrestling Room – Weisiger-Brown Athletic Facility 2500 Warren Carroll Dr, Raleigh, NC 27606', 'Blue practice / @ NC State', NULL, NULL, NULL, NULL, NULL, false, NULL, 'https://w8v0puzioqkz0xzh.public.blob.vercel-storage.com/event-logos/1752372878224.png', NULL, 10, '2025-07-10T14:29:18+00:00'::timestamptz, NOW());

INSERT INTO public.events (title, start_date, end_date, start_time, end_time, category, location, description, coach, registration_deadline, entry_fee, travel_info, weight_classes, rsvp_required, external_link, logo_url, drop_in_registration_link, max_drop_ins, created_at, updated_at)
VALUES ('Blue Team Practice @ NC State', '2025-07-11'::date, NULL, '13:00:00', '15:00:00', 'blue-practice', 'Weisiger‑Brown Athletic Facility 2500 Warren Carroll Drive, Raleigh, NC 27606', 'Blue practice / NC State', NULL, NULL, NULL, NULL, NULL, false, NULL, 'https://w8v0puzioqkz0xzh.public.blob.vercel-storage.com/event-logos/1752372893636.png', NULL, 10, '2025-07-11T01:20:38+00:00'::timestamptz, NOW());

INSERT INTO public.events (title, start_date, end_date, start_time, end_time, category, location, description, coach, registration_deadline, entry_fee, travel_info, weight_classes, rsvp_required, external_link, logo_url, drop_in_registration_link, max_drop_ins, created_at, updated_at)
VALUES ('Blue Team Practice @ UNC', '2025-09-02'::date, NULL, '13:00:00', '15:00:00', 'blue-practice', '210 South Road, Chapel Hill, NC 27599', NULL, NULL, NULL, NULL, NULL, NULL, false, NULL, 'https://w8v0puzioqkz0xzh.public.blob.vercel-storage.com/event-logos/1756821679259.png', NULL, 10, '2025-09-02T14:01:19+00:00'::timestamptz, NOW());

INSERT INTO public.events (title, start_date, end_date, start_time, end_time, category, location, description, coach, registration_deadline, entry_fee, travel_info, weight_classes, rsvp_required, external_link, logo_url, drop_in_registration_link, max_drop_ins, created_at, updated_at)
VALUES ('Blue Team Practice @ UNC', '2025-07-11'::date, NULL, '13:00:00', '15:00:00', 'blue-practice', '210 South Road, Chapel Hill, NC 27599 ·', 'Blue practice / UNC Wrestling Room / Fetzer hall', NULL, NULL, NULL, NULL, NULL, false, NULL, 'https://w8v0puzioqkz0xzh.public.blob.vercel-storage.com/event-logos/1752372921620.png', NULL, 10, '2025-07-11T01:21:34+00:00'::timestamptz, NOW());

INSERT INTO public.events (title, start_date, end_date, start_time, end_time, category, location, description, coach, registration_deadline, entry_fee, travel_info, weight_classes, rsvp_required, external_link, logo_url, drop_in_registration_link, max_drop_ins, created_at, updated_at)
VALUES ('Blue Team Practice @ UNC', '2025-07-11'::date, NULL, '13:00:00', '15:00:00', 'blue-practice', '210 South Road, Chapel Hill, NC 27599 ·', 'Blue practice / UNC Wrestling Room / Fetzer hall', NULL, NULL, NULL, NULL, NULL, false, NULL, 'https://w8v0puzioqkz0xzh.public.blob.vercel-storage.com/event-logos/1752372930810.png', NULL, 10, '2025-07-11T01:21:11+00:00'::timestamptz, NOW());

INSERT INTO public.events (title, start_date, end_date, start_time, end_time, category, location, description, coach, registration_deadline, entry_fee, travel_info, weight_classes, rsvp_required, external_link, logo_url, drop_in_registration_link, max_drop_ins, created_at, updated_at)
VALUES ('Blue Team Practice @ UNC', '2025-07-11'::date, NULL, '13:00:00', '15:00:00', 'blue-practice', '210 South Road, Chapel Hill, NC 27599 ·', 'Blue practice / UNC Wrestling Room / Fetzer hall', NULL, NULL, NULL, NULL, NULL, false, NULL, 'https://w8v0puzioqkz0xzh.public.blob.vercel-storage.com/event-logos/1752372994385.png', NULL, 10, '2025-07-11T01:21:58+00:00'::timestamptz, NOW());

INSERT INTO public.events (title, start_date, end_date, start_time, end_time, category, location, description, coach, registration_deadline, entry_fee, travel_info, weight_classes, rsvp_required, external_link, logo_url, drop_in_registration_link, max_drop_ins, created_at, updated_at)
VALUES ('Blue Team Practice @ UNC', '2025-09-03'::date, NULL, '13:00:00', '15:00:00', 'blue-practice', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL, 'https://w8v0puzioqkz0xzh.public.blob.vercel-storage.com/event-logos/1756922972591.png', NULL, 10, '2025-09-03T18:09:33+00:00'::timestamptz, NOW());

INSERT INTO public.events (title, start_date, end_date, start_time, end_time, category, location, description, coach, registration_deadline, entry_fee, travel_info, weight_classes, rsvp_required, external_link, logo_url, drop_in_registration_link, max_drop_ins, created_at, updated_at)
VALUES ('NC United Blue Practice 9/28', '2025-09-28'::date, NULL, '13:00:00', '15:00:00', 'blue-practice', 'UNC Fetzer Hall, 210 South Road, Chapel Hill, NC 27599', NULL, NULL, NULL, NULL, NULL, NULL, false, NULL, NULL, NULL, 10, '2025-09-16T15:12:38+00:00'::timestamptz, NOW());

INSERT INTO public.events (title, start_date, end_date, start_time, end_time, category, location, description, coach, registration_deadline, entry_fee, travel_info, weight_classes, rsvp_required, external_link, logo_url, drop_in_registration_link, max_drop_ins, created_at, updated_at)
VALUES ('NC United Blue Practice 10/12', '2025-10-12'::date, NULL, '13:00:00', '15:00:00', 'blue-practice', 'UNC Fetzer Hall, 210 South Road, Chapel Hill, NC 27599', NULL, NULL, NULL, NULL, NULL, NULL, false, NULL, NULL, NULL, 10, '2025-09-16T15:16:44+00:00'::timestamptz, NOW());

INSERT INTO public.events (title, start_date, end_date, start_time, end_time, category, location, description, coach, registration_deadline, entry_fee, travel_info, weight_classes, rsvp_required, external_link, logo_url, drop_in_registration_link, max_drop_ins, created_at, updated_at)
VALUES ('NC United Blue Practice 10/26', '2025-10-26'::date, NULL, '13:00:00', '15:00:00', 'blue-practice', 'UNC Fetzer Hall, 210 South Road, Chapel Hill, NC 27599', NULL, NULL, NULL, NULL, NULL, NULL, false, NULL, NULL, NULL, 10, '2025-09-16T15:18:18+00:00'::timestamptz, NOW());

INSERT INTO public.events (title, start_date, end_date, start_time, end_time, category, location, description, coach, registration_deadline, entry_fee, travel_info, weight_classes, rsvp_required, external_link, logo_url, drop_in_registration_link, max_drop_ins, created_at, updated_at)
VALUES ('NC United Blue Practice 11/2', '2025-11-02'::date, NULL, '13:00:00', '15:00:00', 'blue-practice', 'UNC Fetzer Hall, 210 South Road, Chapel Hill, NC 27599', NULL, NULL, NULL, NULL, NULL, NULL, false, NULL, NULL, NULL, 10, '2025-09-16T15:19:49+00:00'::timestamptz, NOW());

INSERT INTO public.events (title, start_date, end_date, start_time, end_time, category, location, description, coach, registration_deadline, entry_fee, travel_info, weight_classes, rsvp_required, external_link, logo_url, drop_in_registration_link, max_drop_ins, created_at, updated_at)
VALUES ('NC United Blue Practice 9/21', '2025-09-21'::date, NULL, '13:00:00', '15:00:00', 'blue-practice', 'UNC Fetzer Hall, 210 South Road, Chapel Hill, NC 27599', NULL, NULL, NULL, NULL, NULL, NULL, false, NULL, NULL, NULL, 10, '2025-09-16T15:41:29+00:00'::timestamptz, NOW());

INSERT INTO public.events (title, start_date, end_date, start_time, end_time, category, location, description, coach, registration_deadline, entry_fee, travel_info, weight_classes, rsvp_required, external_link, logo_url, drop_in_registration_link, max_drop_ins, created_at, updated_at)
VALUES ('Blue Practice', '2025-11-19'::date, NULL, '13:00:00', '15:00:00', 'blue-practice', 'UNC Fetzer Hall, 210 South Road, Chapel Hill, NC 27599', NULL, NULL, NULL, NULL, NULL, NULL, false, NULL, NULL, NULL, 10, '2025-11-19T18:47:14+00:00'::timestamptz, NOW());

INSERT INTO public.events (title, start_date, end_date, start_time, end_time, category, location, description, coach, registration_deadline, entry_fee, travel_info, weight_classes, rsvp_required, external_link, logo_url, drop_in_registration_link, max_drop_ins, created_at, updated_at)
VALUES ('Blue Practice', '2025-12-15'::date, NULL, '13:00:00', '15:00:00', 'blue-practice', '210 South Road, Chapel Hill, NC 27599 ·', NULL, NULL, NULL, NULL, NULL, NULL, false, NULL, NULL, NULL, 10, '2025-12-15T01:30:08+00:00'::timestamptz, NOW());

INSERT INTO public.events (title, start_date, end_date, start_time, end_time, category, location, description, coach, registration_deadline, entry_fee, travel_info, weight_classes, rsvp_required, external_link, logo_url, drop_in_registration_link, max_drop_ins, created_at, updated_at)
VALUES ('Blue Practice', '2025-11-25'::date, NULL, '13:00:00', '15:00:00', 'blue-practice', 'UNC Fetzer Hall, 210 South Road, Chapel Hill, NC 27599', NULL, NULL, NULL, NULL, NULL, NULL, false, NULL, 'https://w8v0puzioqkz0xzh.public.blob.vercel-storage.com/event-logos/1764256413612.png', NULL, 10, '2025-11-25T19:28:29+00:00'::timestamptz, NOW());

INSERT INTO public.events (title, start_date, end_date, start_time, end_time, category, location, description, coach, registration_deadline, entry_fee, travel_info, weight_classes, rsvp_required, external_link, logo_url, drop_in_registration_link, max_drop_ins, created_at, updated_at)
VALUES ('Blue Practice', '2025-12-16'::date, NULL, '13:00:00', '15:00:00', 'blue-practice', '210 South Road, Chapel Hill, NC 27599 ·', NULL, NULL, NULL, NULL, NULL, NULL, false, NULL, 'https://w8v0puzioqkz0xzh.public.blob.vercel-storage.com/event-logos/1765917641205.png', NULL, 10, '2025-12-16T20:40:41+00:00'::timestamptz, NOW());

INSERT INTO public.events (title, start_date, end_date, start_time, end_time, category, location, description, coach, registration_deadline, entry_fee, travel_info, weight_classes, rsvp_required, external_link, logo_url, drop_in_registration_link, max_drop_ins, created_at, updated_at)
VALUES ('Blue Practice', '2026-01-20'::date, NULL, '13:00:00', '15:00:00', 'blue-practice', 'Fetrzer hall - 210 South Road, Chapel Hill, NC 27599', NULL, NULL, NULL, NULL, NULL, NULL, false, NULL, NULL, NULL, 10, '2026-01-20T21:11:37+00:00'::timestamptz, NOW());

INSERT INTO public.events (title, start_date, end_date, start_time, end_time, category, location, description, coach, registration_deadline, entry_fee, travel_info, weight_classes, rsvp_required, external_link, logo_url, drop_in_registration_link, max_drop_ins, created_at, updated_at)
VALUES ('Blue Practice', '2026-02-23'::date, NULL, '13:00:00', '15:00:00', 'blue-practice', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL, NULL, NULL, 10, '2026-02-23T19:33:31+00:00'::timestamptz, NOW());

INSERT INTO public.events (title, start_date, end_date, start_time, end_time, category, location, description, coach, registration_deadline, entry_fee, travel_info, weight_classes, rsvp_required, external_link, logo_url, drop_in_registration_link, max_drop_ins, created_at, updated_at)
VALUES ('Blue Practice', '2026-02-23'::date, NULL, '13:00:00', '15:20:00', 'blue-practice', '210 South Road, Chapel Hill, NC 27599 ·', NULL, NULL, NULL, NULL, NULL, NULL, false, NULL, NULL, NULL, 10, '2026-02-23T19:34:05+00:00'::timestamptz, NOW());

INSERT INTO public.events (title, start_date, end_date, start_time, end_time, category, location, description, coach, registration_deadline, entry_fee, travel_info, weight_classes, rsvp_required, external_link, logo_url, drop_in_registration_link, max_drop_ins, created_at, updated_at)
VALUES ('Blue Practice', '2026-02-23'::date, NULL, '13:00:00', '15:00:00', 'blue-practice', '210 South Road, Chapel Hill, NC 27599 ·', NULL, NULL, NULL, NULL, NULL, NULL, false, NULL, 'https://w8v0puzioqkz0xzh.public.blob.vercel-storage.com/event-logos/1772200421907.png', NULL, 10, '2026-02-23T19:32:24+00:00'::timestamptz, NOW());

INSERT INTO public.events (title, start_date, end_date, start_time, end_time, category, location, description, coach, registration_deadline, entry_fee, travel_info, weight_classes, rsvp_required, external_link, logo_url, drop_in_registration_link, max_drop_ins, created_at, updated_at)
VALUES ('Blue Practice', '2026-03-06'::date, NULL, '13:00:00', '15:00:00', 'blue-practice', '210 South Road, Chapel Hill, NC 27599 ·', NULL, NULL, NULL, NULL, NULL, NULL, false, NULL, NULL, NULL, 10, '2026-03-06T23:41:34+00:00'::timestamptz, NOW());

INSERT INTO public.events (title, start_date, end_date, start_time, end_time, category, location, description, coach, registration_deadline, entry_fee, travel_info, weight_classes, rsvp_required, external_link, logo_url, drop_in_registration_link, max_drop_ins, created_at, updated_at)
VALUES ('Blue Practice', '2026-04-03'::date, NULL, '13:00:00', '15:00:00', 'blue-practice', '210 South Road, Chapel Hill, NC 27599 ·', NULL, NULL, NULL, NULL, NULL, NULL, false, NULL, NULL, NULL, 10, '2026-04-03T21:43:14+00:00'::timestamptz, NOW());

INSERT INTO public.events (title, start_date, end_date, start_time, end_time, category, location, description, coach, registration_deadline, entry_fee, travel_info, weight_classes, rsvp_required, external_link, logo_url, drop_in_registration_link, max_drop_ins, created_at, updated_at)
VALUES ('Blue Practice', '2026-04-08'::date, NULL, '13:00:00', '15:00:00', 'blue-practice', '210 South Road, Chapel Hill, NC 27599 ·', NULL, NULL, NULL, NULL, NULL, NULL, false, NULL, NULL, NULL, 10, '2026-04-08T02:02:47+00:00'::timestamptz, NOW());

INSERT INTO public.events (title, start_date, end_date, start_time, end_time, category, location, description, coach, registration_deadline, entry_fee, travel_info, weight_classes, rsvp_required, external_link, logo_url, drop_in_registration_link, max_drop_ins, created_at, updated_at)
VALUES ('Blue Practice', '2026-04-08'::date, NULL, '13:00:00', '15:00:00', 'blue-practice', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL, NULL, NULL, 10, '2026-04-08T02:05:20+00:00'::timestamptz, NOW());

INSERT INTO public.events (title, start_date, end_date, start_time, end_time, category, location, description, coach, registration_deadline, entry_fee, travel_info, weight_classes, rsvp_required, external_link, logo_url, drop_in_registration_link, max_drop_ins, created_at, updated_at)
VALUES ('Blue Practice', '2026-04-08'::date, NULL, '13:00:00', '15:00:00', 'blue-practice', '210 South Road, Chapel Hill, NC 27599 ·', NULL, NULL, NULL, NULL, NULL, NULL, false, NULL, NULL, NULL, 10, '2026-04-08T02:06:05+00:00'::timestamptz, NOW());

INSERT INTO public.events (title, start_date, end_date, start_time, end_time, category, location, description, coach, registration_deadline, entry_fee, travel_info, weight_classes, rsvp_required, external_link, logo_url, drop_in_registration_link, max_drop_ins, created_at, updated_at)
VALUES ('NC United Blue Practice 11/9', '2025-11-09'::date, NULL, '14:00:00', '16:00:00', 'blue-practice', 'UNC Fetzer Hall, 210 South Road, Chapel Hill, NC 27599', 'UNC Asst Coach Ben Darmstadt will be running practice.', NULL, NULL, NULL, NULL, NULL, false, NULL, 'https://w8v0puzioqkz0xzh.public.blob.vercel-storage.com/event-logos/1762400345126.png', NULL, 10, '2025-09-16T15:21:48+00:00'::timestamptz, NOW());

INSERT INTO public.events (title, start_date, end_date, start_time, end_time, category, location, description, coach, registration_deadline, entry_fee, travel_info, weight_classes, rsvp_required, external_link, logo_url, drop_in_registration_link, max_drop_ins, created_at, updated_at)
VALUES ('UNC @ NC State The Rivalry Match', '2026-01-21'::date, NULL, '19:00:00', '21:00:00', 'blue-practice', 'Reynolds Coliseum @ NC State', 'Buy Tickets https://gopack.evenue.net/events/WRS', NULL, NULL, NULL, NULL, NULL, false, NULL, NULL, NULL, 10, '2026-01-21T22:56:00+00:00'::timestamptz, NOW());

INSERT INTO public.events (title, start_date, end_date, start_time, end_time, category, location, description, coach, registration_deadline, entry_fee, travel_info, weight_classes, rsvp_required, external_link, logo_url, drop_in_registration_link, max_drop_ins, created_at, updated_at)
VALUES ('Rock Hill Bearcat Invitational', '2025-07-20'::date, NULL, NULL, NULL, 'national-tournament', 'Rock Hill High School, 320 W Springdale Rd, Rock Hill, SC.', 'Rock Hill Bearcat Invitational – High School Wrestling Tournament
The Bearcat Invitational, hosted annually by Rock Hill High School in Rock Hill, South Carolina, is one of the Southeast’s premier in-season high school wrestling tournaments. Held just south of Charlotte, the event consistently draws top teams from across North Carolina, South Carolina, and neighboring states.

📅 2026 Tentative Dates: January 3–4, 2026

📍 Location: Rock Hill High School, Rock Hill, SC

🎯 Format: Individual bracketed tournament with boys and girls divisions

🔥 Competition Highlights
Features a deep field of 40+ high school programs, including multiple state-ranked athletes

Offers early-season, high-level competition that helps wrestlers and teams prepare for postseason success

Well-run two-day format with multiple matches guaranteed and team scoring implications

✅ Participation Details
Open to high school teams by invitation or registration approval

Wrestlers must compete as part of an official school team

Sanctioned and listed on official SC and regional wrestling calendars', NULL, NULL, NULL, NULL, NULL, false, NULL, NULL, NULL, 10, '2025-07-20T19:52:18+00:00'::timestamptz, NOW());

INSERT INTO public.events (title, start_date, end_date, start_time, end_time, category, location, description, coach, registration_deadline, entry_fee, travel_info, weight_classes, rsvp_required, external_link, logo_url, drop_in_registration_link, max_drop_ins, created_at, updated_at)
VALUES ('Knock Out', '2025-07-20'::date, NULL, NULL, NULL, 'national-tournament', NULL, '🏆 Knockout Christmas Classic – High School Wrestling Tournament
The Knockout Christmas Classic is one of the premier in-season high school wrestling tournaments in the country, held annually at the Silver Spurs Arena in Kissimmee, Florida. This elite-level competition attracts top programs from across the Southeast and beyond.

🔹 Tournament Details
Dates: December 19–20, 2025

Location: Silver Spurs Arena, Kissimmee, FL

Divisions: High School Boys & Girls (no open or individual entries)

🔒 Participation Requirements
High School Team Entry Only – Wrestlers must compete as part of an officially recognized high school program.

Official School Schedule – Participation must be approved by your school’s athletic director or administration and included on the official competition schedule.

Tournament Approval – All teams must be approved by Knockout tournament staff following registration. Entry is limited and highly competitive.

AAU Membership Required – All wrestlers and coaches must have valid AAU cards prior to the event.

No Unattached or Club Entries – Independent or club wrestlers are not permitted. This is strictly a high school team event.', NULL, NULL, NULL, NULL, NULL, false, NULL, 'https://w8v0puzioqkz0xzh.public.blob.vercel-storage.com/event-logos/1753039646570.jpeg', NULL, 10, '2025-07-20T19:27:26+00:00'::timestamptz, NOW());

INSERT INTO public.events (title, start_date, end_date, start_time, end_time, category, location, description, coach, registration_deadline, entry_fee, travel_info, weight_classes, rsvp_required, external_link, logo_url, drop_in_registration_link, max_drop_ins, created_at, updated_at)
VALUES ('AAU Scholastic Duals', '2025-09-23'::date, NULL, NULL, NULL, 'ncu-dual-tournament', 'Fort Lauderdale', NULL, NULL, NULL, NULL, NULL, NULL, false, NULL, NULL, NULL, 10, '2025-09-23T12:54:12+00:00'::timestamptz, NOW());

INSERT INTO public.events (title, start_date, end_date, start_time, end_time, category, location, description, coach, registration_deadline, entry_fee, travel_info, weight_classes, rsvp_required, external_link, logo_url, drop_in_registration_link, max_drop_ins, created_at, updated_at)
VALUES ('NHSCA HS Nationals', '2025-09-23'::date, NULL, NULL, NULL, 'national-tournament', 'Virginia Beach, VA', NULL, NULL, NULL, NULL, NULL, NULL, false, NULL, 'https://w8v0puzioqkz0xzh.public.blob.vercel-storage.com/event-logos/1758632334568.jpeg', NULL, 10, '2025-09-23T12:58:55+00:00'::timestamptz, NOW());

INSERT INTO public.events (title, start_date, end_date, start_time, end_time, category, location, description, coach, registration_deadline, entry_fee, travel_info, weight_classes, rsvp_required, external_link, logo_url, drop_in_registration_link, max_drop_ins, created_at, updated_at)
VALUES ('NHSCA Duals', '2025-09-23'::date, NULL, NULL, NULL, 'ncu-dual-tournament', 'Virginia Beach, VA', NULL, NULL, NULL, NULL, NULL, NULL, false, NULL, 'https://w8v0puzioqkz0xzh.public.blob.vercel-storage.com/event-logos/1758632551833.jpeg', NULL, 10, '2025-09-23T13:02:32+00:00'::timestamptz, NOW());

INSERT INTO public.events (title, start_date, end_date, start_time, end_time, category, location, description, coach, registration_deadline, entry_fee, travel_info, weight_classes, rsvp_required, external_link, logo_url, drop_in_registration_link, max_drop_ins, created_at, updated_at)
VALUES ('⛔ NCAA Recruiting - Recruiting Shutdown', '2025-07-20'::date, NULL, NULL, NULL, 'ncaa-recruiting', NULL, 'Holiday shutdown for wrestling programs', NULL, NULL, NULL, NULL, NULL, false, NULL, NULL, NULL, 10, '2025-07-20T20:13:55+00:00'::timestamptz, NOW());

INSERT INTO public.events (title, start_date, end_date, start_time, end_time, category, location, description, coach, registration_deadline, entry_fee, travel_info, weight_classes, rsvp_required, external_link, logo_url, drop_in_registration_link, max_drop_ins, created_at, updated_at)
VALUES ('NCAA Recruiting - NCAA Eligibility Center Registration Recommended', '2025-07-20'::date, NULL, NULL, NULL, 'ncaa-recruiting', NULL, 'Athletes entering their junior year should register at the NCAA Eligibility Center to begin academic and amateurism certification. Required for official visits and signing.', NULL, NULL, NULL, NULL, NULL, false, NULL, NULL, NULL, 10, '2025-07-20T20:08:37+00:00'::timestamptz, NOW());

INSERT INTO public.events (title, start_date, end_date, start_time, end_time, category, location, description, coach, registration_deadline, entry_fee, travel_info, weight_classes, rsvp_required, external_link, logo_url, drop_in_registration_link, max_drop_ins, created_at, updated_at)
VALUES ('NCAA Recruiting - NCCA DI & II Recruiting Contact Opens (rising juniors)', '2025-07-20'::date, NULL, NULL, NULL, 'ncaa-recruiting', NULL, 'College coaches can begin directly contacting rising juniors via phone, text, email, and social media 12:00 AM. They can also schedule unofficial and official visits, and make verbal offers.', NULL, NULL, NULL, NULL, NULL, false, NULL, NULL, NULL, 10, '2025-07-20T20:01:40+00:00'::timestamptz, NOW());

INSERT INTO public.events (title, start_date, end_date, start_time, end_time, category, location, description, coach, registration_deadline, entry_fee, travel_info, weight_classes, rsvp_required, external_link, logo_url, drop_in_registration_link, max_drop_ins, created_at, updated_at)
VALUES ('Super32', '2025-07-11'::date, NULL, NULL, NULL, 'national-tournament', 'Greensboro Collesium', 'Super 32 is the nation’s toughest preseason tournament — registration fills fast and opens in late summer, with early qualifiers and strict entry requirements.', NULL, NULL, NULL, NULL, NULL, false, NULL, 'https://w8v0puzioqkz0xzh.public.blob.vercel-storage.com/event-logos/1752370857523.png', NULL, 10, '2025-07-11T16:29:55+00:00'::timestamptz, NOW());

INSERT INTO public.events (title, start_date, end_date, start_time, end_time, category, location, description, coach, registration_deadline, entry_fee, travel_info, weight_classes, rsvp_required, external_link, logo_url, drop_in_registration_link, max_drop_ins, created_at, updated_at)
VALUES ('Dual Team State Finals', '2026-01-15'::date, NULL, NULL, NULL, 'important-date', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL, NULL, NULL, 10, '2026-01-15T00:48:15+00:00'::timestamptz, NOW());

INSERT INTO public.events (title, start_date, end_date, start_time, end_time, category, location, description, coach, registration_deadline, entry_fee, travel_info, weight_classes, rsvp_required, external_link, logo_url, drop_in_registration_link, max_drop_ins, created_at, updated_at)
VALUES ('Ultimate Club Duals', '2025-07-11'::date, NULL, NULL, NULL, 'ncu-dual-tournament', 'Nittany Valley Sports Centre 177 Champion Dr, State College, PA', 'NC United National Team returns to State College, PA for the Ultimate Club Duals! After an impressive showing as Gold Pool finalists in last year''s inaugural event, we''re back with unfinished business — eyes set on bringing home Gold in the Gold. Let''s go NC! 💪🥇', NULL, NULL, NULL, NULL, NULL, false, NULL, 'https://w8v0puzioqkz0xzh.public.blob.vercel-storage.com/event-logos/1752373334500.png', NULL, 10, '2025-07-11T15:39:28+00:00'::timestamptz, NOW());

INSERT INTO public.events (title, start_date, end_date, start_time, end_time, category, location, description, coach, registration_deadline, entry_fee, travel_info, weight_classes, rsvp_required, external_link, logo_url, drop_in_registration_link, max_drop_ins, created_at, updated_at)
VALUES ('Official Start of the NCHSAA Season', '2025-07-13'::date, NULL, NULL, NULL, 'important-date', NULL, 'Official Start Date for Practices', NULL, NULL, NULL, NULL, NULL, false, NULL, 'https://w8v0puzioqkz0xzh.public.blob.vercel-storage.com/event-logos/1752414408007.jpeg', NULL, 10, '2025-07-13T13:46:48+00:00'::timestamptz, NOW());

INSERT INTO public.events (title, start_date, end_date, start_time, end_time, category, location, description, coach, registration_deadline, entry_fee, travel_info, weight_classes, rsvp_required, external_link, logo_url, drop_in_registration_link, max_drop_ins, created_at, updated_at)
VALUES ('NCHSAA State Championships', '2025-07-13'::date, NULL, NULL, NULL, 'important-date', 'Greensboro Coliseum Complex', NULL, NULL, NULL, NULL, NULL, NULL, false, NULL, 'https://w8v0puzioqkz0xzh.public.blob.vercel-storage.com/event-logos/1752374498617.jpeg', NULL, 10, '2025-07-13T02:41:39+00:00'::timestamptz, NOW());

INSERT INTO public.events (title, start_date, end_date, start_time, end_time, category, location, description, coach, registration_deadline, entry_fee, travel_info, weight_classes, rsvp_required, external_link, logo_url, drop_in_registration_link, max_drop_ins, created_at, updated_at)
VALUES ('Beast of The East', '2025-07-20'::date, NULL, NULL, NULL, 'national-tournament', NULL, '🐯 Beast of the East Wrestling Tournament  is one of the premier in-season high school folkstyle tournaments in the U.S., held annually at the Bob Carpenter Center, University of Delaware. 

Dates for December 2025:

Girls'' Beast of the East – December 18–19, 2025

Boys'' Beast of the East – December 20–21, 2025 

The Beast of the East is for high school teams only, requiring admin approval and application via school officials.

Applications typically open in summer/fall—the 2025 Boys'' application closed, Girls'' is open now. 
beastwrestling.com

Weigh-ins and brackets happen on-site; it’s a two-day, elite tournament at Delaware’s Bob Carpenter Center with rigorous competition and team scoring.', NULL, NULL, NULL, NULL, NULL, false, NULL, 'https://w8v0puzioqkz0xzh.public.blob.vercel-storage.com/event-logos/1753039149088.png', NULL, 10, '2025-07-20T19:19:09+00:00'::timestamptz, NOW());

INSERT INTO public.events (title, start_date, end_date, start_time, end_time, category, location, description, coach, registration_deadline, entry_fee, travel_info, weight_classes, rsvp_required, external_link, logo_url, drop_in_registration_link, max_drop_ins, created_at, updated_at)
VALUES ('Journeymen', '2025-07-11'::date, NULL, NULL, NULL, 'national-tournament', 'Schenectady, NY', '🏆 Journeymen Fall Classic – Preseason Elite Wrestling Event
The Journeymen Fall Classic is one of the most competitive preseason wrestling tournaments in the U.S., held each October at Union College in Schenectady, NY. It features top-ranked high school, middle school, and youth wrestlers from across the country.

📅 2025 Dates: October 4–5, 2025

📍 Location: Union College Field House, Schenectady, NY

🎯 Format: Modified round-robin (3–5 matches per athlete)

📺 Coverage: Live and archived on FloWrestling

🔒 Entry Requirements
Coach or club nomination only

Wrestlers must be entered by a recognized coach or club leader

No walk-ups or individual entries; selection is based on credentials (state placers, nationally ranked, etc.)

Limited spots; early entry is strongly encouraged

📝 Apply or Request Entry
Application Page: www.journeymenwrestling.com

Or contact the director via email: info@journeymenwrestling.com', NULL, NULL, NULL, NULL, NULL, false, NULL, NULL, NULL, 10, '2025-07-11T15:44:26+00:00'::timestamptz, NOW());

INSERT INTO public.events (title, start_date, end_date, start_time, end_time, category, location, description, coach, registration_deadline, entry_fee, travel_info, weight_classes, rsvp_required, external_link, logo_url, drop_in_registration_link, max_drop_ins, created_at, updated_at)
VALUES ('Escape The Rock', '2025-07-20'::date, NULL, NULL, NULL, 'national-tournament', 'Council Rock South High School, Holland, PA 18966', '🧗‍♂️ 2026 Escape the Rock – High School Wrestling Tournament

The Escape the Rock is one of the premier in-season individual high school wrestling tournaments in the country. It draws top-ranked wrestlers and powerhouse programs from across the U.S. for a highly competitive two-day event.

📅 Dates: January 17–18, 2026

📍 Location: Council Rock South High School, Holland, PA

🏆 Format: Individual bracketed tournament

🎯 Eligibility: High school athletes only — must be entered through their school’s official wrestling program

🆕 Girls Division: Added for 2026

🔒 Entry Requirements
Wrestlers must be entered by their high school coach or athletic department

Tournament participation must be on the official school schedule

All entries are subject to approval by Escape the Rock staff

No unattached or club entries permitted', NULL, NULL, NULL, NULL, NULL, false, NULL, NULL, NULL, 10, '2025-07-20T19:36:11+00:00'::timestamptz, NOW());

INSERT INTO public.events (title, start_date, end_date, start_time, end_time, category, location, description, coach, registration_deadline, entry_fee, travel_info, weight_classes, rsvp_required, external_link, logo_url, drop_in_registration_link, max_drop_ins, created_at, updated_at)
VALUES ('Southeast Open', '2025-07-20'::date, NULL, NULL, NULL, 'college-open', 'Cregger Center, Roanoke College, Salem, VA', 'Description:
Established in 2008, the Southeast Open has become one of the premier season-opening college tournaments in the nation. This event features an elite field packed with NCAA Division I, II, and III programs and is known for launching successful college campaigns.

This tournament is designed for seasoned veterans and high-level prospects ready to compete at the next level. Only our most elite NC United athletes should consider entering.

Opportunities make champions—this is where they begin.', NULL, NULL, NULL, NULL, NULL, false, NULL, NULL, NULL, 10, '2025-07-20T18:33:43+00:00'::timestamptz, NOW());

INSERT INTO public.events (title, start_date, end_date, start_time, end_time, category, location, description, coach, registration_deadline, entry_fee, travel_info, weight_classes, rsvp_required, external_link, logo_url, drop_in_registration_link, max_drop_ins, created_at, updated_at)
VALUES ('NC Super 32 Early Entry', '2025-09-03'::date, NULL, NULL, NULL, 'national-tournament', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL, NULL, NULL, 10, '2025-09-03T18:13:59+00:00'::timestamptz, NOW());

INSERT INTO public.events (title, start_date, end_date, start_time, end_time, category, location, description, coach, registration_deadline, entry_fee, travel_info, weight_classes, rsvp_required, external_link, logo_url, drop_in_registration_link, max_drop_ins, created_at, updated_at)
VALUES ('Dual Team States Round 1 & 2', '2026-01-15'::date, NULL, NULL, NULL, 'important-date', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL, NULL, NULL, 10, '2026-01-15T00:57:28+00:00'::timestamptz, NOW());

INSERT INTO public.events (title, start_date, end_date, start_time, end_time, category, location, description, coach, registration_deadline, entry_fee, travel_info, weight_classes, rsvp_required, external_link, logo_url, drop_in_registration_link, max_drop_ins, created_at, updated_at)
VALUES ('Dual Team States Rounds 3 & 4', '2026-01-15'::date, NULL, NULL, NULL, 'important-date', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL, NULL, NULL, 10, '2026-01-15T00:47:38+00:00'::timestamptz, NOW());

INSERT INTO public.events (title, start_date, end_date, start_time, end_time, category, location, description, coach, registration_deadline, entry_fee, travel_info, weight_classes, rsvp_required, external_link, logo_url, drop_in_registration_link, max_drop_ins, created_at, updated_at)
VALUES ('Wilkes Open', '2025-07-20'::date, NULL, NULL, NULL, 'college-open', '236 S. River St., Wilkes‑Barre, PA 18702', 'Established over 90 years ago and often called the "Rose Bowl of Wrestling," the Wilkes Open is one of the longest-running and most competitive early-season college tournaments in the country. It features a deep and diverse field with NCAA Division I, II, and III programs, along with select unattached high school athletes competing at the elite level.

This open-format tournament provides a rare opportunity for high school standouts to test themselves against seasoned collegiate competition. Past participants have included programs like Appalachian State, Duke, Davidson, Alvernia, Wilkes, and Penn College.

💥 Highly recommended for experienced, nationally competitive wrestlers only.', NULL, NULL, NULL, NULL, NULL, false, NULL, NULL, NULL, 10, '2025-07-20T19:04:02+00:00'::timestamptz, NOW());

INSERT INTO public.events (title, start_date, end_date, start_time, end_time, category, location, description, coach, registration_deadline, entry_fee, travel_info, weight_classes, rsvp_required, external_link, logo_url, drop_in_registration_link, max_drop_ins, created_at, updated_at)
VALUES ('Super32', '2026-01-13'::date, NULL, NULL, NULL, 'national-tournament', 'Greensboro Coliseum Complex', NULL, NULL, NULL, NULL, NULL, NULL, false, NULL, NULL, NULL, 10, '2026-01-13T15:12:06+00:00'::timestamptz, NOW());

INSERT INTO public.events (title, start_date, end_date, start_time, end_time, category, location, description, coach, registration_deadline, entry_fee, travel_info, weight_classes, rsvp_required, external_link, logo_url, drop_in_registration_link, max_drop_ins, created_at, updated_at)
VALUES ('NCHSAA Regionals', '2026-01-15'::date, NULL, NULL, NULL, 'important-date', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL, NULL, NULL, 10, '2026-01-15T00:45:07+00:00'::timestamptz, NOW());

INSERT INTO public.events (title, start_date, end_date, start_time, end_time, category, location, description, coach, registration_deadline, entry_fee, travel_info, weight_classes, rsvp_required, external_link, logo_url, drop_in_registration_link, max_drop_ins, created_at, updated_at)
VALUES ('Women''s Regionals', '2026-01-15'::date, NULL, NULL, NULL, 'important-date', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL, NULL, NULL, 10, '2026-01-15T00:48:46+00:00'::timestamptz, NOW());

INSERT INTO public.events (title, start_date, end_date, start_time, end_time, category, location, description, coach, registration_deadline, entry_fee, travel_info, weight_classes, rsvp_required, external_link, logo_url, drop_in_registration_link, max_drop_ins, created_at, updated_at)
VALUES ('🔍 NCAA Recruiting - Free FAFSA Opens for Class of 2026', '2025-07-20'::date, NULL, NULL, NULL, 'ncaa-recruiting', NULL, 'The FAFSA form (Free Application for Federal Student Aid) becomes available for rising seniors. Vital for athletes seeking need-based aid or combining athletic + academic aid at D-II/NAIA/D-III schools.', NULL, NULL, NULL, NULL, NULL, false, NULL, NULL, NULL, 10, '2025-07-20T20:16:13+00:00'::timestamptz, NOW());

INSERT INTO public.events (title, start_date, end_date, start_time, end_time, category, location, description, coach, registration_deadline, entry_fee, travel_info, weight_classes, rsvp_required, external_link, logo_url, drop_in_registration_link, max_drop_ins, created_at, updated_at)
VALUES ('NCAA Recruiting - Official Visit Eligibility Opens', '2025-07-20'::date, NULL, NULL, NULL, 'ncaa-recruiting', NULL, 'Wrestlers may start official visits to D‑I and D‑II programs. No limit on the number of visits overall, but only one visit per school (two allowed if a coaching change occurs)', NULL, NULL, NULL, NULL, NULL, false, NULL, NULL, NULL, 10, '2025-07-20T20:04:33+00:00'::timestamptz, NOW());

INSERT INTO public.events (title, start_date, end_date, start_time, end_time, category, location, description, coach, registration_deadline, entry_fee, travel_info, weight_classes, rsvp_required, external_link, logo_url, drop_in_registration_link, max_drop_ins, created_at, updated_at)
VALUES ('⛔ NCAA Recruiting - Dead Period', '2025-07-20'::date, NULL, NULL, NULL, 'ncaa-recruiting', NULL, 'No in-person recruiting contact during NLI signing week. Coaches may use phone/email. Specifically for wrestling', NULL, NULL, NULL, NULL, NULL, false, NULL, NULL, NULL, 10, '2025-07-20T20:12:31+00:00'::timestamptz, NOW());

COMMIT;
